[server]
backlog = 2048
http_port = 20000
keep_alive = 5
max_connection_rate = 1024
max_connections = 100000
max_frame_size = 134217728
workers = 8

[master_client]
endpoints = ["localhost:8081"]

[pusher]
pusher_mgr_capacity = 100000

[puller]
check_interval = 60
idle_timeout = 300
max_offset_dif = 1000
max_seconds_elapsed = 300
puller_mgr_capacity = 100000

[db]
path = "data"
ttl = 300

[db.seriesdb]
level_zero_file_num_compaction_trigger = 4
max_background_jobs = 4
max_bytes_for_level_base = 1073741824
max_bytes_for_level_multiplier = 8.0
max_write_buffer_number = 4
min_write_buffer_number_to_merge = 2
table_cache_num_shard_bits = 4
target_file_size_base = 134217728
target_file_size_multiplier = 8
write_buffer_size = 134217728
